name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - "terraform.tfvars"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}

    steps:
      - name: Checkout Deployment Repo
        uses: actions/checkout@v4

      - name: Install Azure DevOps Extension
        run: |
          az extension add --name azure-devops --yes

      - name: Download Terraform Module
        run: |
          mkdir -p modules/rg_module

          az artifacts universal download \
            --organization "https://dev.azure.com/${{ secrets.ADO_ORG }}" \
            --project "${{ secrets.ADO_PROJECT }}" \
            --scope project \
            --feed "${{ secrets.ADO_FEED }}" \
            --name "rg-module" \
            --version "*" \
            --path "./modules/rg_module"

      - name: Verify Download
        run: |
          find modules -type f

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
